---
driver:
  name: vagrant

provisioner:
  name: chef_zero

driver_config:
  require_chef_omnibus: true

platforms:
  - name: ubuntu-14.04
    run_list:
    - recipe[apt::default]
  - name: ubuntu-12.04
    run_list:
    - recipe[apt::default]

- name: centos-6.5
  driver_config:
    box: opscode-centos-6.5
    box_url: https://opscode-vm-bento.s3.amazonaws.com/vagrant/opscode_centos-6.5_provisionerless.box

- name: centos-5.9
  driver_config:
    box: opscode-centos-5.9
    box_url: https://opscode-vm-bento.s3.amazonaws.com/vagrant/opscode_centos-5.9_provisionerless.box

suites:
- name: default
  run_list:
  - recipe[motd-tail]
  attributes: {}
