AllCops:
  Exclude:
    - vendor/**/*

AlignParameters:
  Enabled: false

Encoding:
  Enabled: false

LineLength:
  Max: 200

# Offense count: 1
# Configuration parameters: Exclude.
FileName:
  Enabled: false
